- LICENSE
Add the author to the Apache license. This should have been done at license creation, but was missed as it isn't done automatically by GitHub for Apache as it is for BSD3 and MIT.
> Add copyright holder to license

- README.md
Add Scikit-HEP project badge to README
[![Scikit-HEP](https://scikit-hep.org/assets/images/Scikit--HEP-Project-blue.svg)](https://scikit-hep.org/)
additionally, add a GitHub badge that redirects back to the GitHub repo so that if the README is rendered on PyPI there is a clear link back in the page (in addition to the link)
[![GitHub Project](https://img.shields.io/badge/GitHub--blue?style=social&logo=GitHub)](https://github.com/scikit-hep/pylhe)
```
* Add Scikit-HEP project badge
* Add badge linked to GitHub repo
```
> docs: Add Scikit-HEP project badge to README

- pyproject.toml
Use the new directory ignore pattern of `check-manifest` introduced in [`v0.42`](https://github.com/mgedmin/check-manifest/blob/master/CHANGES.rst#042-2020-05-03).
> You can ignore directories only by ignoring every file inside it. You can use `--ignore=dir/**` to do that
```
* Use check-manifest ignore pattern introduced in v0.42
```
> fix: Use check-manifest v0.42 directory ignore pattern

- docker/Dockerfile
Easier to debug for not much more space, and also allows for direct installation of SciPy and NumPy.
For the PR Assignees:
```
* Use python:3.7-slim as base image for Docker image builds
- Allows for greater flexibility and easier reproducibility of user results and errors
```
> chore: Use Debian based python:3.7-slim as base Docker image

- .github/workflows/ci.yml
- setup.py
Add a 'test' extra to `setup.py` to make it easier to revise and install all of the dependencies needed to run the tests.
```
* Add 'test' extra
* Use 'test' extra in CI
```
> feat: Add 'test' extra to setup.py

- .flake8
- .github/workflows/ci.yml
- .pre-commit-config.yaml
- setup.py
Given that [`flake8`](https://gitlab.com/pycqa/flake8) uses `pyflakes` but offers more configuration control adopt use of `flake8` for linting.
```
* Add flake8 to 'test' extra and .pre-commit-config.yaml
* Add .flake8 configuration file
- flake8 does not yet support pyproject.toml
* Use flake8 for linting in CI
```
> feat: Use flake8 for linting

- src/pylhe/__init__.py
An option to read the optional event information with `readLHEWithAttributes` and a corresponding field in `LHEEvent` was added. This optional event information is defined in the Les Houches file format according to [A Standard format for Les Houches event files](https://inspirehep.net/literature/725284) section 4.
> Add option to read optional event information

- .github/workflows/publish-package.yml
- pyproject.toml
- setup.py
Adopt the pyhf publication CI workflow to publish pylhe to PyPI with teach push of a tag to `master` and to TestPyPI with each push to `master`.
This requires @lukasheinrich to first setup API tokens as `${{ secrets.test_pypi_password }}` and `${{ secrets.pypi_password }}` for TestPyPI and PyPI. This is detailed in Issue #19, but @lukasheinrich can ask me if there are any questions.
```
* Add publishing workflow to GitHub Actions for TestPyPI and PyPI using API tokens
* Add build system info required for PEP 517 type build
```
> ci: Add CI to publish to PyPI with each tag release

- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .github/workflows/publish-package.yml
- setup.py
Create a separate `lint` extra that can be used to lint the codebase in a separate GitHub Actions workflow then the testing of the codebase. This should allow for faster testing overall, and it also allows for linting to not block development flow until a PR is finished.
For the PR Assignees:
```
* Add 'lint' extra to setup.py
* Move linting into a separate GitHub Actions workflow
- Only run lint workflow on pull_request events
* Move MANIFEST check to publish-package workflow
- Move check-manifest to 'develop' extra
```
> ci: Separate linting from testing

- README.md
After the codecov works now, the badge can be published via the `README.md`. (Think this should be a fast one now ;)
> chore: Add Codecov coverage badge

- .bumpversion.cfg
- .zenodo.json
- README.md
Add a preferred BibTeX citation to README that gets updated with releases through `bumpversion`. Additionally, add control over metadata shown on Zenodo through `.zenodo.json`.
```
* Add preferred BibTeX citation to README
* Add .zenodo.json to control metadata for releases on Zenodo
* Control the citation information through bumpversion
```
> docs: Add preferred BibTeX citation to README

- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .github/workflows/publish-package.yml
```
* Add workflow dispatch to all GitHub Action workflows
* Update to Python 3.8 in package publishing workflow
* Update to v1.3.1 of the pypa/gh-action-pypi-publish action in package publishing workflow
```
> ci: Add workflow dispatch support and update actions

- .pre-commit-config.yaml
```
* Update Black pre-commit hook to use rev v20.8b1
- Using pinned revs is the recommended approach for pre-commit: https://github.com/psf/black/issues/420
* Update flake8 pre-commit hook to use rev v3.8.3
```
> chore: Update pre-commit hook revs

- setup.py
[`bumpversion` is no longer maintained](https://github.com/peritus/bumpversion) (as of apparently November 2019). Given this we should probably take the project's advice
> 🎬 If you want to start using `bumpversion`, you're best advised to install one of the maintained forks, e.g. ➡ @ c4urself's [`bump2version`](https://github.com/c4urself/bump2version/#installation).
This PR migrates to using `bump2version` `v1.X` release series.
**Suggested squash and merge commit message:**
```
* Add bump2version to the develop extra
- bumpversion is no longer maintained and bump2version is the recommended fork
- Use bump2version v1.X series
* Migrate flake8 to the lint extra
```
> chore: Migrate to bump2version

- .github/workflows/lint.yml
- setup.py
Use `flake8` to lint the codebase in the `lint` GitHub Actions workflow.
```
* Use flake8 in the lint workflow
* Remove pyflakes form the lint extra
```
> ci: Use flake8 in lint workflow

- setup.cfg
- src/pylhe/__init__.py
* pypdt's particle() will return None for SUSY PDG IDs in 0.7.5
* backslash needs to be escaped twice
* networkx 1.11 has write_dot in submodule (no guarantees about this fix)
> feat: Use particle for labeling in visualizations

- .github/workflows/publish-package.yml
This PR uses publication type releases to publish to PyPI by running the publication workflow on `published` `release` events and then verifying that the PyPI upload step is running on one. This follows what I'll call the `corner` model (which I now think is how GitHub Actions assumed people would do things): 
This follows the example that @dfm has setup in [`corner`](https://github.com/dfm/corner.py) with running the workflow on [`published` `release` events](https://github.com/dfm/corner.py/blob/efd25380ee121c4d565ed9aff2f98e184cc9dcef/.github/workflows/tests.yml#L7-L8) and then only running the [publish to PyPI step on that conditions](https://github.com/dfm/corner.py/blob/efd25380ee121c4d565ed9aff2f98e184cc9dcef/.github/workflows/tests.yml#L82). To instigate this workflow one would do …
> ci: Publish releases to PyPI through GitHub releases

- .github/workflows/publish-package.yml
With the old workflow if the publishing workflow was run after a new tag was created
```
$ bump2version <part>
$ git push origin master --tags
```
no release would get published to TestPyPI as the workflow that would get kicked off from the `push` event to `master` (and so NOT a `tag` event) would fail the "Verify untagged commits have dev versions" step
https://github.com/scikit-hep/pylhe/blob/dd781b7040df6d5638c71ab880f19be76eb512b2/.github/workflows/publish-package.yml#L37-L47
as it would
https://github.com/scikit-hep/pylhe/blob/dd781b7040df6d5638c71ab880f19be76eb512b2/.github/workflows/publish-package.yml#L38
but then also `"${wheel_name}" != *"dev"*` given that it comes from a tag. So nothing gets published.
Similarly, the workflow that would get kicked off from the `tag` event will …
> fix: Don't run publishing workflow on tags to avoid errors

- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .github/workflows/publish-package.yml
- setup.cfg
```
* Add testing of Python 3.9 runtime to CI
* Change default Python runtime for all GitHub Action workflows to Python 3.9
* Add Python 3.9 support to PyPI metadata
```
> test: Add Python 3.9 to CI

- .github/workflows/ci.yml
- setup.cfg
- src/pylhe/__init__.py
- tests/test_visualize.py
Partially addresses Issue #43 
In preparation of `v0.1.0` drop Python 2.7 support and support for Python 3 older than 3.6
```
* Require Python 2.7 or later or Python 3.6+ for install
* Add Python 2.7 to PyPI metadata
- To be dropped after v0.1.0 is published
* Temporarily loosen networkx requirements to >=2.2 to allow for Python 2.7 install
- Test Python 2.7 until v0.1.0 is published
* Temporarily explicitly wrap paths as str and remove use of f-strings until Python 2 dropped
```
> fix: Require Python 2.7 or later or Python 3.6+

- .github/workflows/ci.yml
- setup.cfg
- src/pylhe/__init__.py
- tests/test_visualize.py
Resolves #43 
```
* Drop support of Python 2.7 and require Python 3.6 or newer
- Remove Python 2 PyPI metadata
- Drop testing of Python 2.7
* Remove Python 2.7 specific stopgap fixes
```
> feat: Drop Python 2.7 support

- README.md
[![DOI](https://zenodo.org/badge/34966492.svg)](https://zenodo.org/badge/latestdoi/34966492)
```
* Have Zenodo badge point to all releases DOI
- c.f. https://doi.org/10.5281/zenodo.1217031
```
> docs: Fix Zenodo DOI badge

- setup.cfg
- setup.py
To give releases longer stability and lifetimes upper bounds are required on core dependencies to ensure that breaking API changes to not break old releases. This is a builtin functionality of [PEP 440's compatible release syntax](https://www.python.org/dev/peps/pep-0440/#compatible-release). This PR applies compatible release syntax (`~=`) to all of the dependencies in `install_requires`, establishing lower bounds from when they were added and similarly upper bounds.
---
[Quick summary of compatible release syntax](https://github.com/mwouts/jupytext/pull/596):
In [PEP 440's "Compatible release" section](https://www.python.org/dev/peps/pep-0440/#compatible-release)
> For a given release identifier V.N, the compatible release clause is approximately equivalent to the pair of comparison …
> build: Use compatible release syntax to give ranges for install_requires

- setup.cfg
Trivial update to latest series. Not that the updates will matter to you here, but no harm in using the latest and greatest.
(In fact explicit support for Python 3.9 only came with the 0.13 series, so better update in any case.)
> build: Use Particle v0.14 for minimal compatible release

- .pre-commit-config.yaml
Add pre-commit hooks for [`pre-commit-hooks`](https://github.com/pre-commit/pre-commit-hooks) ("Some out-of-the-box hooks for pre-commit.") [recommended by the Scikit-HEP developer guide](https://scikit-hep.org/developer/style#pre-commit).
```
* Add pre-commit hooks for pre-commit-hooks recommended by Scikit-HEP
- c.f. https://github.com/pre-commit/pre-commit-hooks
- c.f. https://scikit-hep.org/developer/style#pre-commit
```
> ci: Add pre-commit hooks from pre-commit-hooks recommended by Scikit-HEP

- setup.cfg
```
* Remove universal wheel setting as pylhe is Python 3 only
- Fixes py2.py3 tag naming scheme for wheels
```
> build: Remove universal wheel flag

- src/pylhe/__init__.py
- tests/test_lhe_reader.py
Resolves #65 
```
* Add support for reading gzip-ed files by first opening gzip files if passed in to the readLHE APIs
- Use _extract_fileobj with a context manager for the readLHE APIs
* Add tests for reading behavior 
Co-authored-by: Lukas <lukas.heinrich@gmail.com>
```
> feat: Add support for reading compressed files

- src/pylhe/__init__.py
- tests/test_lhe_reader.py
Resolves #79 
```
* Add support for reading gzipped files to pylhe.readNumEvents
* Add test to compare pylhe.readNumEvents output for LHE files and gzipped LHE files
* Amends PR #74
```
> fix: Have all read APIs accept gzipped files

- src/pylhe/__init__.py
- tests/test_api.py
Implemented from Brett Cannon's blog [An approach to lazy importing in Python 3.7](https://snarky.ca/lazy-importing-in-python-3-7/) and implemented it for `hist` in https://github.com/scikit-hep/hist/pull/179:
> I’ve used Python 3.7 module-level `__getattr__` for a while now to allow mistyping hist.axis import as hist.axes to show a warning but work anyway. However, I completely missed a fantastic usage for Python 3.7 module-level `__dir__ `: you can “fix” IPython’s tab completion to just show the items in `__all__`! Wow! One of the main things that bugged me about importing and defining unrelated things in modules, and one reason that boost-histogram has an `_internal` module.
c.f. https://github.com/scikit-hep/pyhf/issues/1402
Used in PR #83 
For the PR Assignees:
```
* Use module level …
```
> feat: Use module level __dir__ to restrict public API views

- .github/workflows/publish-package.yml
Remove the option `--sdist --wheel` from 
https://github.com/scikit-hep/pylhe/blob/d35bb3212d8b150c83527bdbf8426b93d6a2ccdd/.github/workflows/publish-package.yml#L32-L34
to enable the default behavior for `build` in release `v0.5.0` of building a sdist and then building a wheel from the sidst to ensure that the sdist is capable of building a wheel. This was added in https://github.com/pypa/build/pull/304
```console
$ pip list | grep build
build       0.5.0
$ python -m build --help
usage: python -m build [-h] [--version] [--sdist] [--wheel] [--outdir OUTDIR] [--skip-dependency-check] [--no-isolation] [--config-setting CONFIG_SETTING] [srcdir]
A simple, correct PEP 517 package builder.
By default, a source distribution (sdist) is built from {srcdir}
and a binary distribution (wheel) is …
```
> ci: Remove distribution options to enable default build v0.5.0 behavior

- .bumpversion.cfg
- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .gitignore
- pyproject.toml
- setup.cfg
- src/pylhe/__init__.py
- tests/test_api.py
This bumps us up to a more modern version of `setuptools_scm` that supports `pyproject.toml` and will inject the right version at build time (via PEP517/8) as well as generate the corresponding `version.py` for us at build time.
c.f. https://github.com/scikit-hep/pyhf/pull/1450 for motivation
For the PR Assignees:
```
* Update to a modern version of setuptools_scm to support pyproject-based Python packages
- Use local_scheme = "no-local-version" to continue uploading to TestPyPI
- c.f. https://github.com/pypa/setuptools_scm/blob/v6.0.1/README.rst#version-number-construction
* Add `pylhe.__version__` to API
* Generate src/pylhe/_version.py at build time
- Remove setup.cfg from bump2version control
* Set fetch depth:0 in CI to get full history and tags to generate version number
- c.f. …
```
> chore: Use newer setuptools_scm for versioning

- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .github/workflows/publish-package.yml
```
* Add Python 3.10 to testing matrix in CI
- Use quotes on '3.10' to avoid YAML returning a value of 3.1
* List contents of sdist and wheel during packaging build test
* Use normal installs instead of editable installs for testing
```
> ci: Update CI to test with Python 3.10

- .pre-commit-config.yaml
```
* Use black-jupyter hook over nbqa-black
* Sync pre-commit additional_dependencies for pyupgrade
- Amends PR #107
```
> chore: Sync pre-commit additional_dependencies and use black-jupyter hook

- pyproject.toml
You need at least setuptools 42 to use pyproject.toml, and attrs is not needed at build time. Also, wheel is declared by PEP 517's get_requires_for_build_sdist, which setuptools declares.
> build: Require setuptools v42.0.0+ for stability

- setup.cfg
Indeed support for Python 3.10 was added in https://github.com/scikit-hep/pylhe/pull/105 but the setup.cfg qualifiers did not reflect that.
While at it I also moved to being more "demanding" on the `Particle` package dependency to ensure that PDG 2021 is used by default, which seems fine (I realise a new version is typically picked up but for formality I made the explicit upgrade).
```
* Add Python 3.10, Python 3 only, and Developers to classifiers
metadata for PyPI.
```
> build: Add Python 3.10 to PyPI metadata

- setup.cfg
c.f. https://github.com/scikit-hep/pyhf/pull/1382 for description of general motivation.
Also updates lower bound on `particle` as originally recommended in PR #108.
```
* Place only lower bounds (>=) on all core dependencies in setup.cfg.
* Update lower bond on particle to v0.16 to ensure compliance with the
2021 version of the PDG.
Co-authored-by: Eduardo Rodrigues <eduardo.rodrigues@cern.ch>
```
> build: Set only lower bounds on core dependencies

- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .github/workflows/publish-package.yml
```
* Update GitHub Action workflows:
- Use actions/checkout v3 for all workflows.
https://github.com/actions/checkout/releases/tag/v3.0.0
- Use actions/setup-python v3 for all workflows.
https://github.com/actions/setup-python/releases/tag/v3.0.0
- Use codecov/codecov-action v2.
https://github.com/codecov/codecov-action/releases/tag/v2.1.0
- Use pypa/gh-action-pypi-publish v1.5.0.
https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.5.0
```
> ci: Update GitHub Actions to new stable versions

- .github/workflows/ci.yml
```
* Report coverage on all triggering GitHub Actions events except
on 'schedule' events.
- This allows for coverage to be reported on PRs opened from
outside of scikit-hep.
* Report coverage on oldest and newest Python tested.
* Run CI on push events to 'master'.
```
> ci: Report coverage on push and pull requests

- .github/workflows/semantic-pr-check.yml
As https://github.com/zeke/semantic-pull-requests is no longer maintained and is down (c.f. https://github.com/zeke/semantic-pull-requests/issues/183#issuecomment-1137844183), use the suggested alternative of https://github.com/amannn/action-semantic-pull-request to check that PR titles follow the Conventional Commits spec.
```
* As https://github.com/zeke/semantic-pull-requests is no longer maintained
and is down, use the suggested alternative of
https://github.com/amannn/action-semantic-pull-request to check that PR titles
follow the Conventional Commits spec.
```
> ci: Add semantic PR check GHA workflow

- .pre-commit-config.yaml
- src/pylhe/__init__.py
```
* Change all explicit relative imports to absolute imports.
- Provides clearer more explicit imports for new developers.
* Add absolufy-imports to pre-commit hooks
```
> refactor: Use absolute imports over explicit relative imports

- .bumpversion.cfg
- setup.py
- tbump.toml
```
* Add tbump to 'develop' extra and remove bump2version.
* Add tbump.toml to configure tbump.
- Allow for valid versions to follow SemVer and also support release
candidates: <major>.<minor>.<patch>rc<candidate>
* Remove .bumpversion.cfg.
```
> feat: Use tbump over bump2version

- .zenodo.json
* Lukas Heinrich is a professor at Technical University of Munich as of March 2022.
* Matthew Feickert is a postdoc at University of Wisconsin-Madison as of June 2022.
> docs: Update dev team affiliations

- README.md
Relates to task https://github.com/scikit-hep/pylhe/issues/30 on package documentation.
> docs: Add a 'get started' example to the README

- .github/workflows/bump-version.yml
* Add tbump based bump version workflow for managing release tags from GitHub Actions workflow dispatch. The workflow adds support for:
- bumping versions, creating tags, pushing the tags back to GitHub
- release candidates as viable options
- automated checks that the SemVer type of bump (major, minor, patch),
and if it was or wan't a release candidate, makes sense given the
latest tags available on GitHub and the new tag number entered
- dry runs (the default) to test that your options all look good
> ci: Add bump version workflow for release tags

- src/pylhe/__init__.py
I noticed that the `read_lhe` type of functions and others, which parse the XML, do not all catch parsing errors. This PR makes things more homogeneous. Note that
1. On purpose I am not trying here to deal with test coverage of these parsing errors. That's something to be done with a dedicated PR and will require a special LHE file, if not several.
2.  We should discuss at some point if parsing errors should raise errors or be dealt with smoothly, as now, with print statements. Again, I think it is better to make any modification to the way these errors are dealt with homogeneously across the various methods.
> feat: more homogeneous usage of ParseError

- tests/test_classes.py
- tests/test_lhe_reader.py
First batch of work to achieve reasonable coverage for the main package functionality.
What is missing is largely coverage for exceptions, the scope of issue https://github.com/scikit-hep/pylhe/issues/142.
```
* Add tests for fromstring methods.
* Add tests for read_lhe functions.
```
> test: Extend coverage of classes and add cover of read_lhe

- README.md
The badges updated will now show in orange as for example in `Particle`s README.
```
* Add conda-forge badge to README
- c.f. https://github.com/conda-forge/pylhe-feedstock
```
> docs: Add Conda badge to README

- .github/dependabot.yml
* Add GitHub Dependabot config to check for GitHub Action version updates and to open PRs if available. Set the check and update interval to weekly.
- c.f. https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
> ci: Enable Dependabot version updates for GitHub Actions

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- setup.cfg
```
* Require Python 3.7 for install.
* Drop Python 3.6 from testing in CI.
* Enforce Python 3.7+ syntax in pyupgrade.
```
Once Python 3.11 support is added (there is a small bug that can be fixed) and this is merged we could cut `v0.5.0` to get a clean Python version drop on a minor release.
> build: Support Python 3.7+

- .github/workflows/publish-package.yml
Resolves #151
* Publish to TestPyPI on push events where a tag is pushed that starts with a 'v' (release tags of form vX.Y.Z) or on workflow dispatch events where the maintainer running the workflow has selected the 'true' option from the drop-down menu for whether to publish.
- The workflow dispatch option defaults to 'false' to avoid accidental publishing.
* Update development docs to reflect that not every commit is published to TestPyPI
> ci: Publish to TestPyPI on tag or by workflow dispatch trigger

- src/pylhe/__init__.py
- tests/test_visualize.py
The current code on `main` tries to catch a `KeyError` if a ID is not in the PDG to LaTeX name look up `DirectionalMap`, but the `DirectionalMap` throws a `MatchingIDNotFound` exception when it cannot find an ID.
This bug means that users cannot generate a graph with non-standard PDG IDs in them.
It is a simple patch to fix up this bug and allow for IDs not in the table to simple be represented by their ID number.
**Squash and merge commit message**
```
* Use MatchingIDNotFound exception over KeyError to allow for non-standard PDG
IDs to be used.
* Add test for handling non-standard PDG IDs.
```
> fix: Update KeyError to new exception of DirectionalMap

- .github/workflows/ci.yml
- setup.cfg
- src/pylhe/__init__.py
- src/pylhe/awkward.py
- tests/test_api.py
* Drop support for Python 3.7 and require Python 3.8+ for use.
* Remove guard for Python 3.7+ from tests.
> build: Require Python 3.8+

- setup.py
- src/pylhe/__init__.py
- tests/test_lhe_reader.py
powheg uses plain text weights in lhe, like: 
```
<event>
7  10001  1.11453E+07  2.42132E+00 -1.00000E+00  3.21830E-01
-2    -1     0     0     0   502  0.000000000E+00  0.000000000E+00  1.596673772E-01  1.596673772E-01  0.000000000E+00  0.00000E+00  9.000E+00
21    -1     0     0   502   501  0.000000000E+00  0.000000000E+00 -1.979087573E+01  1.979087573E+01  0.000000000E+00  0.00000E+00  9.000E+00
23     2     1     2     0     0 -2.715131942E-01 -6.004246500E-01 -3.272239123E+00  3.504354871E+00  1.067110589E+00  0.00000E+00  9.000E+00
11     1     3     3     0     0 -9.921110112E-02  2.574546034E-01 -3.072708859E-01  4.129665530E-01  5.110000000E-04  0.00000E+00  9.000E+00
-11     1     3     3     0     0 -1.723020930E-01 -8.578792534E-01 -2.964968237E+00  3.091388318E+00 …
```
> feat: Add support for POWHEG weights

- src/pylhe/__init__.py
> fix: Do not overwrite `rwgt` weights with `weights` weights

- src/pylhe/__init__.py
`LHEInit` and `LHEProcInfo` inherit from `dict`. When parsing a string to either of them with `fromstring` it should return the corresponding class not a generic dict. They should have the same `__init__` function as a `dict` for convenience.
```
* `LHEInit` and `LHEProcInfo` inherit from `dict`. When parsing a string
to either of them with `fromstring` it should return the corresponding
class not a generic dict. They should have the same `__init__` function
as a `dict` for convenience.
```
> fix: dict classes should produce instances of themselves

- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .github/workflows/publish-package.yml
- docker/Dockerfile
- setup.cfg
* Add Python 3.12 to CI tests.
* Make the default Python for CI be Python 3.12.
* Add Python 3.12 classifier metadata.
* Use python:3.12-slim as the base Docker image.
> ci: Add Python 3.12 to testing

- .github/workflows/bump-version.yml
- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .github/workflows/publish-package.yml
- docker/Dockerfile
* Use 'uv pip install --system' in CI to speed up installs.
> ci: Use uv for all pip installs

- .github/workflows/publish-package.yml
- pyproject.toml
* Add generation of GitHub artifact attestations to built sdist and wheel before upload. c.f.:
- https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/
- https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds
* Add verification of artifact attestation before publishing to PyPI using the 'gh attestation verify' CLI API, added in v2.49.0.
- c.f. https://github.com/cli/cli/releases/tag/v2.49.0
> ci: Add GitHub artifact attestations to package distribution

- .github/workflows/lint.yml
- .github/workflows/publish-package.yml
* Use 'pipx run' to avoid having to install tools into the same environment.
> ci: Use 'pipx run' to simplify installs

- .zenodo.json
- CITATION.cff
- tbump.toml
* Add Citation File Format file to repo to get repository cite button on GitHub.
- c.f. https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files
* Add CITATION.cff to tbump control.
> docs: Add CITATION.cff Citation File Format file

- .zenodo.json
- CITATION.cff
- README.md
- pyproject.toml
* Add Alexander Puck Neuwirth as a project maintainer and add him to the author lists.
> docs: Add Alexander Puck Neuwirth as maintainer

- src/pylhe/__init__.py
- src/pylhe/awkward.py
- tests/test_api.py
- tests/test_awkward.py
> refactor: Remove register_awkward()

- .github/workflows/ci.yml
- pyproject.toml
Adding 3.13, which was released today.
> chore: add 3.13 classifier and test

- .github/workflows/bump-version.yml
* Allow @APN-Pucky to bump versions for releases.
> ci: Add Alexander Neuwirth to publisher list

- src/pylhe/__init__.py
Fixes the bug in Issue #281 
Not sure we have a good test at the moment though.
> fix: Add missing comma in LHEInit fieldnames

- src/pylhe/__init__.py
- tests/test_lhe_reader.py
Test script to monitor memory usage (based on https://github.com/scikit-hep/pylhe/issues/213#issue-1869374586):
```py
import pylhe
import psutil
import os
afile = "examples/weighted.lhe.gz"
process = psutil.Process(os.getpid())
prev_rss = None
prev_vms = None
for ievt, evt in enumerate(pylhe.read_lhe(afile)):  # pylhe.read_lhe_with_attributes
if ievt % 100000 == 0:
mem_info = process.memory_info()
rss_mb = mem_info.rss / (1024 * 1024)
vms_mb = mem_info.vms / (1024 * 1024)
print(f"\nEvent {ievt}")
print(f"RSS: {rss_mb:.2f} MB", end='')
if prev_rss is not None:
print(f" (Δ {rss_mb - prev_rss:+.2f} MB)")
else:
print()
print(f"VMS: {vms_mb:.2f} MB", end='')
if prev_vms is not None:
print(f" (Δ {vms_mb - prev_vms:+.2f} MB)")
else:
print()
prev_rss = rss_mb
prev_vms = vms_mb
```
where …
> fix: memory increase
